### ISSUE TITLE
Change chicken settings along with Belt configs for Map Script.  In Kolbot

### ISSUE THREAD

**Issue by B2d2** [DetectiveSquirrel/Kolbot-MapThread#1]
I am having a problem setting up Mh part,   loads and works but as soon i use a Number for the script to "go where ever"  it uses all my potions if they are not the same as my Mf char.  Also i would like to cancel chicken setting when using maphack.  Do i need to create new lead b4 and edit and change 
the script to map in the kolbot manager to activate files?  Im going to try and create a new profile and disable chicken which i believe may work but the belt configurations will still be an issue if i use mh on different types of charators.   Nothing shows up in the D2 BotMap dbj that looks editable.         Just had a thought, can i comment out "//" the belt config if i used a diff char for Mh??  will bot still function.  I will try it.  If there is a different way i would appriciate some help.      Thank you for all that you do!!!   B2d2

**Comment by DetectiveSquirrel** [comment]
make a custom config (see kolbot wiki "char config" at the bottom) and change hp/mp usage settings. it loads the same config as it would if it was botting. just change pot usage settings in w/e config its loading.
